name: CI
on:
  pull_request:
  push:
    branches: master
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NEO4J_EDITION_FLAG: -e
      NEO4J_VERSION: 4.3.3
      driver: ruby
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'
    - uses: BSFishy/pip-action@v1
      with:
        packages: git+https://github.com/klobuczek/boltkit@1.3#egg=boltkit
    - name: Setup seabolt
      run: |
        sudo apt-get install -y libssl1.1
        wget https://github.com/neo4j-drivers/seabolt/releases/download/v1.7.4/seabolt-1.7.4-Linux-ubuntu-$(lsb_release -rs).deb
        dpkg -i seabolt-1.7.4-Linux-ubuntu-$(lsb_release -rs).deb
        rm seabolt-1.7.4-Linux-ubuntu-$(lsb_release -rs).deb
    - name: Setup Neo4j
      run: |
        neoctrl-install $NEO4J_EDITION_FLAG $NEO4J_VERSION servers
        if [ -n "$NEO4J_EDITION_FLAG" ]; then NEO4J_EDITION=enterprise; else NEO4J_EDITION=community; fi
        NEO4J_DIR=servers/neo4j-$NEO4J_EDITION-$NEO4J_VERSION
        neoctrl-configure $NEO4J_DIR dbms.memory.pagecache.size=600m dbms.memory.heap.max_size=600m dbms.memory.heap.initial_size=600m dbms.directories.import= dbms.connectors.default_listen_address=:: dbms.security.auth_enabled=false
        neoctrl-start $NEO4J_DIR
    - name: Install dependencies
      run: bundle update
    - name: Rspec
      run: bundle exec rspec
    - name: Upload coverage results
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: coverage-report
        path: coverage
